config/routes.rb
Rails.application.routes.draw do

#this app was created by Ankush Malik github:  https://github.com/freakuency
 

  get '/professional_profile' => 'friendships#index'
  get 'ignore_friendships' => 'friendships#ignore'
  get '/friendships/destroy/:user_id' => 'friendships#destroy'
  get 'create_friendships' => 'friendships#create'
  get 'accept_friendships' => 'friendships#accept'
  root 'users#index'
  get '/users' => 'users#index'
  post '/users/register' => 'users#register'
  post '/users/login'
  post '/users' => 'users#logout'
  get '/users/show' => 'users#show_all'
  get "/users/:user_id" => "users#show"
  get '/slot1' => "slots#slot1"
  get '/slot2' => "slots#slot2"
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships, dependent: :destroy


  email_regex = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i
  alphabet = /\A[a-zA-Z]+\z/
  validates :email, :presence => true, :format => { :with => email_regex }, :uniqueness => { :case_sensitive => false }
  validates :name, :presence => true, :format => {:with => alphabet }
  validates :description, :presence => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #this app was created by Ankush Malik github:  https://github.com/freakuency
  protect_from_forgery with: :exception
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
#this app was created by Ankush Malik github:  https://github.com/freakuency

  def index

   
    @user = User.find(session[:user_id])
    @friends = @user.friends
    @user_all = User.all 
    @friendship_all = Friendship.all 
    @invites = Friendship.where(friend_id:session[:user_id], status: "Pending")
    @accept = Friendship.where(friend_id:session[:user_id], status: "Accepted")
  end

  def create
    $sid= params[:sid]
    Friendship.create(user: User.find(session[:user_id]), friend: User.find(params[:user_id]), status:"Pending")
    redirect_to '/professional_profile'
  end


  def destroy #bidirectional deletion
   Friendship.find_by(user_id: User.find(session[:user_id]), friend_id: User.find(params[:user_id])).destroy 
   Friendship.find_by(user_id: User.find(params[:user_id]), friend_id:User.find(session[:user_id])).destroy 
   redirect_to '/professional_profile'
  end

  def accept #bidirectional addition
    $sac=params[:sac]
    @user = User.find(session[:user_id])
    Friendship.find_by(id: params[:id]).update(status:"Accepted")
    Friendship.create(user: @user , friend: User.find(params[:user_id]), status:"Accepted")
    redirect_to '/professional_profile'
  end 
  def ignore
    Friendship.find_by(id: params[:id]).destroy 
    redirect_to '/professional_profile'
  end 
end

app/controllers/slots_controller.rb
class SlotsController < ApplicationController
	def slot1
		
	end
	def slot2
		
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def register
	  	@user = User.create(name:params[:name],email:params[:email],password:params[:password],password_confirmation:params[:password_confirmation], description:params[:description])
	  	if @user.valid?
	  		session[:user_id] = @user.id
	  		redirect_to '/professional_profile'
	  	else
	  		redirect_to '/users', :notice => @user.errors.full_messages
	  end 
  end

  def login
  		if !params[:email].blank? && !params[:password].blank?
  		user = User.find_by_email(params[:email])
	  	if user 
	  		if  user.authenticate(params[:password])
	  			session[:user_id] = user.id
	  			redirect_to '/professional_profile'
	  		else 
	  			redirect_to '/users', :alert =>  "Email/password do not match. Try again."
	  		end
	  	else
	  		redirect_to '/users', :alert =>  "Email does not exist."
	  	end
	  else
	  	redirect_to '/users', :alert =>  "Email and Password cannot be blank."
	  end
  end

   def show_all
    @users = User.all 
    @current_user = User.find(session[:user_id])
    @friendships = @current_user.friends
    @pending = Friendship.where(status: "Pending", friend_id:session[:user_id])

    #you dont want to be friend with yourself :P
   	
    @all_friends = []
    for pend in @pending  
    	@all_friends.push(pend.user_id)
    end 

    puts"*"*100
    puts @all_friends.class
    puts"*"*100
	end

  def show
  @user= User.find(params[:user_id])
  end 

  def logout
    session[:user_id] = nil
    redirect_to '/users'
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friend_requests_helper.rb
module FriendRequestsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/slots_helper.rb
module SlotsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friendships/edit.html.erb
<h1>Friendships#edit</h1>
<p>Find me in app/views/friendships/edit.html.erb</p>

app/views/friendships/index.html.erb
<div class='container'>
	<div class='header'> 
		<h2> Welcome, <%= @user.name %>! </h2>
		<form action="/users" method="POST">
			<input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">
	 		<input class="button" type='submit' value='Logout' style="color: white;"> 
	 	</form>
	</div>
	<div id="page_wrapper">
		<p>
		<!-- FOR ADMIN TO INVITE OTHER USERS FOR ACCESSING SLOTS :- -->
	<!-- 	<%if @user.id==2%>
		 <a href="/users/show" class="button" style="margin-bottom:10px;text-decoration:none;" > All Users </a>
		<%end%> 
	-->
		</p>
		<div style="height:10px"></div>
		<% if @user.id==2%>
				<h4> users Accessing slots right now:- </h4>
				<% for user in @user_all %>
					<% for pending in @accept%>
					 <% if user.id == pending.user_id %>
					 	<p><a href="/users/<%= user.id%>" style="text-decoration:none;"><%= user.name %></a></p>
						<div style="height:10px"></div>

					 	<a href="/friendships/destroy/<%= pending.user_id%>" class="button" style="text-decoration:none;">Remove</a></p>
					 	<%end%>
					 <%end%>
				<%end%> 
				<div style="height:30px"></div>
			<h4> The following people have asked you for accessing the slots</h4>
			<%for pending in @invites%>
			<%if pending.user.id!=nil%>
				<div style="height:15px"></div>
				  <% for user in @user_all%>
					<% for pending in @invites%>
					 <% if user.id == pending.user_id %>
					 	<p style="font-size:20px;padding-left:15px;"> <a href="/users/<%= user.id%>" style="text-decoration:none;color:black"> > <%= user.name%> for the slot number : <%= $sid%></a></p>
						<div style="height:10px"></div>
					 	<%= link_to "Accept",accept_friendships_path(:id=>pending[:id],:user_id=>pending[:user_id],:sac=>$sid),class: "button"%>
					 	<%= link_to "Ignore",ignore_friendships_path(:id=>pending[:id]),class: "button"%>
					 	<%end%>
					 <%end%>
					 <%end%>
				<%end%> 
				<%end%> 
		<%else%>
			<%chk=Friendship.where(friend_id:2,status: "Accepted") %>
			<%a=chk.pluck(:user_id)%>
			<%count=0%>
			<%a.each do |u|%>
				<%if u==@user.id%>
				 <%count=count+1%>
				<%end%>
			<%end%>
			<%if count!=0%>
				<%if $sac=='1'%>
				<%= link_to "slot_1",slot1_path, class: "button"%><br><div style="height:20px;"></div>
				<%= link_to "slot_2","/professional_profile",data: {confirm: "Access Denied"},class: "button"%>
				<%elsif $sac=='2'%>
				<%= link_to "slot_1","/professional_profile",data: {confirm: "Access Denied !"},class: "button"%>
				<%= link_to "slot_2",slot2_path, class: "button"%><div style="height:50px;"></div>
				<%end%>
				<% for user in @user_all %>
				  <% for pending in @accept%>
					 <% if user.id == pending.user_id %>
					  <h4> Admin has granted your request for accessing the slot </h4>
					  <p><a href="/users/<%= user.id%>" style="text-decoration:none;"><%= user.name %></a></p>
						<div style="height:10px"></div>
					  <a href="/friendships/destroy/<%= pending.user_id%>", class="button" style="text-decoration:none;">Remove</a></p>
					 <%end%>
					<%end%>
				<%end%> 
			<%else%>
				<%= link_to "slot_1","/professional_profile",data: {confirm: "Access Denied !"},class: "button"%>
				<br>
				<div style="height:20px"></div>
				<%= link_to "send request for slot",create_friendships_path(:user_id=>2,:sid=>1),class: "button" %>
				<div style="height:40px"></div>
				<%= link_to "slot_2","/professional_profile",data: {confirm: "Access Denied"},class: "button"%>
				<br><div style="height:20px"></div>
				<%= link_to "send request for slot",create_friendships_path(:user_id=>2,:sid=>2), class: "button"%>
				<% for user in @user_all %>
					<% for pending in @accept%>
					 <% if user.id == pending.user_id %>
					 <h4> Admin has granted your request for accessing the slot </h4>
					 	<p><a href="/users/<%= user.id%>" class="button" style="text-decoration:none;"><%= user.name %></a></p>
					 	<a href="/friendships/destroy/<%= pending.user_id%>" style="text-decoration:none;" class="button">Remove</a></p>
					 <%end%>
					<%end%>
				<%end%> 
			<%end%>
			<%for pending in @invites%>
			<%if pending.user.id!=nil%>
				<div style="height:15px"></div>
				  <% for user in @user_all%>
					<% for pending in @invites%>
					 <% if user.id == pending.user_id %>
					 	<p style="font-size:20px;padding-left:15px;"> <a href="/users/<%= user.id%>" style="text-decoration:none;color:#2980B9"> > <%= user.name %></a></p>
						<div style="height:10px"></div>
					 	<a href="/friendships/accept/<%= pending.id%>/<%= pending.user_id%>" class="button" style="text-decoration:none;">Accept</a>
					 	<a href="/friendships/ignore/<%= pending.id%>" class="button" style="text-decoration:none;">Ignore</a></td>
					 	<%end%>
					 <%end%>
					 <%end%>
				<%end%> 
				<%end%> 

		<%end%>
		

	</div>
	
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>slot_aproval_project</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href="https://fonts.googleapis.com/css?family=Raleway:400,700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="bckimg">

<%= yield %>

</div>
</body>
</html>

app/views/slots/slot1.html.erb
 <h2 style="margin-bottom:15px;">this is first Video slot :</h2>
 <p><%= link_to "back","friendships/destroy/2",class: :button%></p>
<iframe width="100%" height="550" src="https://www.youtube.com/embed/HBoM0drk7xU?autoplay=1" frameborder="0" allowfullscreen></iframe>

app/views/slots/slot2.html.erb
 <h2>this is second text slot:</h2>
 <br>
 <p><%= link_to "back","friendships/destroy/2",class: :button%></p>
 <div contenteditable style="font: 2rem/1.5 monospace;max-width:60rem;margin:0 auto;padding:4rem;"></div>

app/views/users/index.html.erb
<div class="kik">
<div class="header">
<h2>Slot Project!</h2>
<form action="/users/login" method="POST" style="padding-top:8px">
		<input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">
			<input placeholder=" Email" type="text" name="email" style="height:25px">
			<input placeholder=" Password" type="password" name="password" style="height:25px">
		<input class="button" type="submit" value="Login" style="color:white;">
	</form>
</div>
<div id="page_wrapper" class="box" style="">
	<div id="flash">
		
	<% if flash[:notice] %>
	<div style="border-left:solid 1.5px white;border-right:solid 1.5px white;border-radius:10px;">
	<% flash[:notice].each do |message| %>
		<ul style="padding-left:10px;list-style:none;">
		<li style="padding-top:5px;color:white;"> > <%= message %></li>
		</ul>
	<% end %>
	</div>
	<% end %>

	<% if flash[:alert] %>
	<p><%= flash[:alert] %></p>
	<% end %>
	</div>

	<div class="login">
	<h1 style="padding-bottom:15px">Register</h1>
	<form action="/users/register" method="POST">
	<span>
		<input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" style="height:25px">
		<input placeholder="  Name" type="text" name="name" style="height:30px"><br>
		<input placeholder="  Email" type="text" name="email" style="height:30px"><br>
		<input placeholder="  Password" type="password" name="password" style="height:30px"><br>
		<input placeholder="  Confirm Password" type="password" name="password_confirmation" style="height:30px"><br>
		<input placeholder="  Description" type="text" name="description" style="height:30px"><br>
	</span>
		<p><input class="button" type="submit" value="Register" style="margin-top:20px;color:white;"></p>
	</form>
	</div>
</div>
</div>

app/views/users/show.html.erb
<div id="page_wrapper">
	<p> <a href="/professional_profile" class="button" style="margin:10px;"> Back </a></p>
<div style="height:30px;"></div>
		<form action="/users/logout" method="POST">
			<input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">
	 		<input type='submit' value='Logout' class="button"> 
	 		</form>
<div style="height:30px;"></div>

<h2> > Name : <%= @user.name %> </h2>
<h4> > Description :<%= @user.description %> </h4>
</div>

app/views/users/show_all.html.erb
<div id="page_wrapper">
	
	<h4> Users you may want to Invite for the accessing the slots: </h4>

	<table>
		<tr>
			<th> Name </th>
			<th> Action </th>
		</tr>

		<tr>
		
		<% @users.each do |user| %>
		<% if @current_user.id != user.id and !@friendships.include? (user) and ! @all_friends.include? (user.id) %>
		<td> <a href="/users/<%= user.id%>"> <%= user.name %> </a> </td>
		<td> <a href="/friendships/create/<%= user.id%>">Connect</a></td>
		<div style="height:10px;"></div>
		</tr>
		<%end%>
		<%end%>
	</table>
	<div style="height:30px;"></div>
	<a href="/professional_profile" class="button"> Back </a>



</div>